var number = 205.35;
//console.log( number.toFixed(2) );
//console.log( number.toExponential() );
//console.log( number.toPrecision(2) );
//console.log( number.toString() );
//console.log ( Math.sqrt(81) );
//console.log ( Math.pow(5,2) );
//console.log ( Math.floor(number) );
//console.log ( Math.ceil(number) );
//console.log ( Math.round(number) );
console.log ( Math.PI );